### Send GET request to get all blogs
GET http://localhost:3003/api/blogs

### Send POST request create new blog
POST http://localhost:3003/api/blogs
Authorization: Bearer $2b$10$Epbb0cYgyKBkVaZVDGgph.GH80bruqRnvY/L/XbmrY3EV6GQBzacm
Content-Type: application/json

{
  "title": "El titulo2",
  "author": "El autor2",
  "url": "La url2",
  "likes": 0
}

### Send POST request to create a new user
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "El usuario",
  "email": "email@adsf.com",
  "password": "lapass"
}

### Send POST request to login
POST http://localhost:3003/api/users/login
Content-Type: application/json

{
  "username": "El usuario",
  "password": "lapass"
}